//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestaurant.Domain.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RestaurantMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RestaurantMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRestaurant.Domain.Messages.RestaurantMessages", typeof(RestaurantMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غذا قبلا دریافت شده است.
        /// </summary>
        public static string MealAlreadyReceived {
            get {
                return ResourceManager.GetString("MealAlreadyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت غذا.
        /// </summary>
        public static string MealExceptions_Title {
            get {
                return ResourceManager.GetString("MealExceptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غذایی با این نام قبلا تعریف شده است.
        /// </summary>
        public static string MealNameExists {
            get {
                return ResourceManager.GetString("MealNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام غذا الزامی است.
        /// </summary>
        public static string MealNameRequired {
            get {
                return ResourceManager.GetString("MealNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت وعده غذایی.
        /// </summary>
        public static string MealPeriodExceptions_Title {
            get {
                return ResourceManager.GetString("MealPeriodExceptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان وارد شده برای وعده غذایی غیرمنطقی است.
        /// </summary>
        public static string MealPeriodInvalidTime {
            get {
                return ResourceManager.GetString("MealPeriodInvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وعده غذایی با این نام قبلا تعریف شده است.
        /// </summary>
        public static string MealPeriodNameExists {
            get {
                return ResourceManager.GetString("MealPeriodNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام وعده غذایی الزامی است.
        /// </summary>
        public static string MealPeriodNameRequired {
            get {
                return ResourceManager.GetString("MealPeriodNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعضی از غذاهای انتخابی در منوی روز تعریف نشده‌اند.
        /// </summary>
        public static string MealsNotInMenuForDayPeriod {
            get {
                return ResourceManager.GetString("MealsNotInMenuForDayPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع غذا الزامی است.
        /// </summary>
        public static string MealTypeRequired {
            get {
                return ResourceManager.GetString("MealTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف منوی جدید برای تاریخ‌های گذشته ممکن نیست.
        /// </summary>
        public static string MenuDateInThePast {
            get {
                return ResourceManager.GetString("MenuDateInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت منو.
        /// </summary>
        public static string MenuExceptions_Title {
            get {
                return ResourceManager.GetString("MenuExceptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنلی با این کد قبلا تعریف شده است.
        /// </summary>
        public static string PersonnelCodeExists {
            get {
                return ResourceManager.GetString("PersonnelCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنل الزامی است.
        /// </summary>
        public static string PersonnelCodeRequired {
            get {
                return ResourceManager.GetString("PersonnelCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت پرسنل.
        /// </summary>
        public static string PersonnelExceptions_Title {
            get {
                return ResourceManager.GetString("PersonnelExceptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پرسنل الزامی است.
        /// </summary>
        public static string PersonnelNameRequired {
            get {
                return ResourceManager.GetString("PersonnelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت رزرو جدید برای تاریخ‌های گذشته ممکن نیست.
        /// </summary>
        public static string ReserveDateInThePast {
            get {
                return ResourceManager.GetString("ReserveDateInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت رزرو.
        /// </summary>
        public static string ReserveExceptions_Title {
            get {
                return ResourceManager.GetString("ReserveExceptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای پیش‌بینی نشده.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
