//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestaurant.Framework.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrameworkMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRestaurant.Framework.Messages.FrameworkMessages", typeof(FrameworkMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای فیلتر.
        /// </summary>
        internal static string InvalidFilterException {
            get {
                return ResourceManager.GetString("InvalidFilterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی فیلتر اشتباه است (ورودی صحیج: تاریخ).
        /// </summary>
        internal static string InvalidFilterExpectedDate {
            get {
                return ResourceManager.GetString("InvalidFilterExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی فیلتر اشتباه است (ورودی صحیج: آرایه تاریخ).
        /// </summary>
        internal static string InvalidFilterExpectedDateArray {
            get {
                return ResourceManager.GetString("InvalidFilterExpectedDateArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی فیلتر اشتباه است (ورودی صحیج: عدد).
        /// </summary>
        internal static string InvalidFilterExpectedNumber {
            get {
                return ResourceManager.GetString("InvalidFilterExpectedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی فیلتر اشتباه است (ورودی صحیج: آرایه اعداد).
        /// </summary>
        internal static string InvalidFilterExpectedNumericArray {
            get {
                return ResourceManager.GetString("InvalidFilterExpectedNumericArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی فیلتر اشتباه است (ورودی صحیج: رشته متنی).
        /// </summary>
        internal static string InvalidFilterExpectedString {
            get {
                return ResourceManager.GetString("InvalidFilterExpectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فیلتر با فیلد همخوانی ندارد.
        /// </summary>
        internal static string InvalidFilterType {
            get {
                return ResourceManager.GetString("InvalidFilterType", resourceCulture);
            }
        }
    }
}
