//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestaurant.Framework.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRestaurant.Framework.Exceptions.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در پایگاه داده رخ داده است.
        /// </summary>
        internal static string Database_Description {
            get {
                return ResourceManager.GetString("Database_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای پایگاه داده.
        /// </summary>
        internal static string Database_Title {
            get {
                return ResourceManager.GetString("Database_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این اطلاعات توسط کاربر دیگری تغییر کرده است. لطفا اطلاعات را مجدد دریافت کنید.
        /// </summary>
        internal static string DatabaseConcurrency_Description {
            get {
                return ResourceManager.GetString("DatabaseConcurrency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تغییر کرده است.
        /// </summary>
        internal static string DatabaseConcurrency_Title {
            get {
                return ResourceManager.GetString("DatabaseConcurrency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از اطلاعات مورد نیاز وارد نشده است.
        /// </summary>
        internal static string DatabaseDataRequired_Description {
            get {
                return ResourceManager.GetString("DatabaseDataRequired_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای الزام ورود اطلاعات.
        /// </summary>
        internal static string DatabaseDataRequired_Title {
            get {
                return ResourceManager.GetString("DatabaseDataRequired_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از مقادیر وارد شده بیش از حد مجاز است.
        /// </summary>
        internal static string DatabaseDataTooLong_Description {
            get {
                return ResourceManager.GetString("DatabaseDataTooLong_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اطلاعات.
        /// </summary>
        internal static string DatabaseDataTooLong_Title {
            get {
                return ResourceManager.GetString("DatabaseDataTooLong_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مقدار قبلا ثبت شده است.
        /// </summary>
        internal static string DatabaseDuplicate_Description {
            get {
                return ResourceManager.GetString("DatabaseDuplicate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داده.
        /// </summary>
        internal static string DatabaseDuplicate_Title {
            get {
                return ResourceManager.GetString("DatabaseDuplicate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان انجام این عملیات وجود ندارد زیرا این داده با اطلاعات دیگری مرتبط است.
        /// </summary>
        internal static string DatabaseForeignKeyViolation_Description {
            get {
                return ResourceManager.GetString("DatabaseForeignKeyViolation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ارتباط داده‌ها.
        /// </summary>
        internal static string DatabaseForeignKeyViolation_Title {
            get {
                return ResourceManager.GetString("DatabaseForeignKeyViolation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز لازم برای دسترسی به منبع یا صفحه مورد نظر وجود ندارد.
        /// </summary>
        internal static string Forbidden_Description {
            get {
                return ResourceManager.GetString("Forbidden_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی غیرمجاز.
        /// </summary>
        internal static string Forbidden_Title {
            get {
                return ResourceManager.GetString("Forbidden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منبع مورد نظر یافت نشد.
        /// </summary>
        internal static string NotFound_Description {
            get {
                return ResourceManager.GetString("NotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیدا نشد.
        /// </summary>
        internal static string NotFound_Title {
            get {
                return ResourceManager.GetString("NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ابتدا نسبت به احراز هویت اقدام نمایید.
        /// </summary>
        internal static string UnAuthorized_Description {
            get {
                return ResourceManager.GetString("UnAuthorized_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم احراز هویت.
        /// </summary>
        internal static string UnAuthorized_Title {
            get {
                return ResourceManager.GetString("UnAuthorized_Title", resourceCulture);
            }
        }
    }
}
